# Generated by Django 5.2.3 on 2025-07-09 02:55

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0005_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.IntegerField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
            ],
        ),
    ]
