# Generated by Django 5.1.6 on 2025-04-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0002_remove_article_created_at_article_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
    ]
