# Generated by Django 5.1.6 on 2025-04-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0003_remove_article_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.IntegerField()),
                ("summary", models.TextField()),
            ],
        ),
    ]
