# Generated by Django 5.2.3 on 2025-07-09 00:51

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0004_summary"),
    ]

    operations = [
        VectorExtension()
    ]
